[package]

name = "coreaudio-rs"
version = "0.0.5"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>"]
description = "A friendly rust interface for Apple's CoreAudio API."
keywords = ["core", "audio", "unit", "osx", "ios"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/RustAudio/coreaudio-rs.git"
homepage = "https://github.com/RustAudio/coreaudio-rs"

[dependencies]
coreaudio-sys = "*"
libc = "*"
