[package]

name = "coreaudio-rs"
version = "0.1.1"
authors = ["mitchmindtree <mitchell.nordine@gmail.com>", "yupferris <jake@fusetools.com>"]
description = "A friendly rust interface for Apple's CoreAudio API."
keywords = ["core", "audio", "unit", "osx", "ios"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/RustAudio/coreaudio-rs.git"
homepage = "https://github.com/RustAudio/coreaudio-rs"


[dev-dependencies]
num = "0.1.27"

[dependencies]
coreaudio-sys = "0.1.1"
libc = "0.1.10"
